counsel: add tab switcher
abo-abo/swiper pull request #2667
Opened 2020-08-28 11:58 UTC by peterhoeg

Allows you to easily switch between open tabs.

2020-08-28 11:58 UTC, peterhoeg commented
CA signed ages ago due to `use-package` contribution.

2020-09-02 07:47 UTC, basil-conto requested changes
Thanks for working on this! See some comments on technicalities below, otherwise LGTM.

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +  (cdr (car (cdr tab))))
This is assuming that `name` is the first element of a tab's alist, but alists are unordered collections. You should instead write:
```el
(cdr (assq 'name tab))
```

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +;;** `counsel-tab-bar'
This section is under `;;* Elisp symbols`, where it does not belong. Please move it under `;; Misc. Emacs` or similar.

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +   "Select tab: "
Nit: perhaps the prompt should convey what `counsel-tab-bar` is going to do with the tab, e.g. `Switch to tab:`.

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +   :Keymap counsel-mode-map
`:Keymap` -> `:keymap`

But I don't think this is right, as `counsel-mode-map` is enabled by `counsel-mode`, not individual completion functions.

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +   (mapcar #'counsel--tab-name (funcall tab-bar-tabs-function))
`tab-bar-tabs-function` and `tab-bar-switch-to-tab` are new in Emacs 27, so in older Emacsen they give byte-compiler warnings like the following:
```
In counsel-tab-bar:
counsel.el:745:41:Warning: reference to free variable ‘tab-bar-tabs-function’

In end of data:
counsel.el:6965:1:Warning: the following functions are not known to be
    defined: tab-bar-switch-to-tab
```
I think the best way to silence these is by adding the following after `(interactive)`:
```el
  (when (< emacs-major-version 27)
    (user-error "This command requires Emacs 27 or later"))
  (defvar tab-bar-tabs-function)
  (declare-function tab-bar-switch-to-tab "tab-bar" (name))
```

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +   :preselect (counsel--tab-name (tab-bar--current-tab))
Please avoid calling internal functions like `tab-bar--current-tab`, as they can come and go and change behaviour without warning. Instead, can't you use the `current-tab` entry returned by `tab-bar-tabs-function`?

Stepping even further back, why preselect the current tab? Doesn't switching to a tab imply that the user wants to switch to a different tab?

2020-09-02 07:47 UTC, basil-conto commented on counsel.el
> +             (tab-bar-switch-to-tab x))
AKA `:action #'tab-bar-switch-to-tab`

2023-11-01 10:09 UTC, peterhoeg commented
@basil-conto my apologies for dropping this after you took the time to review it. I am no longer using counsel, so closing this again.

2023-11-01 10:09 UTC, closed without merging