delete-selection-mode for counsel-yank-pop
abo-abo/swiper pull request #2826
Opened 2021-03-10 01:52 UTC by p1llule

Hi M.abo and M.conto

delete-selection-mode ... well, delete the active region before some
commands, Notably the yank command.

This commit makes it aware of counsel-yank-pop without any further
action from the user (if he is lucky enough to have activated
delete-selection-mode before installing counsel ?).

2021-03-10 23:13 UTC, basil-conto requested changes
Thanks for catching this, `counsel-yank-pop` definitely needs a `delete-selection` property.

See my comments below.

2021-03-10 23:13 UTC, basil-conto commented on counsel.el
> +  :type 'symbolp)
There's no need for a user option:
- Users can toggle this behaviour at runtime using `delete-selection-mode`.
- Built-in `yank-pop` unconditionally has a `delete-selection` property.

2021-03-10 23:13 UTC, basil-conto commented on counsel.el
> +  (put #'counsel-yank-pop 'delete-selection counsel-yank-delete-selection))
It's better to minimise side-effects at load-time.  I think you should put:

```el
(put #'counsel-yank-pop 'delete-selection 'yank)
```

right after `(defun counsel-yank-pop ...)`.

If `delete-selection-mode` is disabled, the symbol property is a no-op anyway.

2021-03-13 09:48 UTC, p1llule commented
fine, thanks for the insights.

2021-03-13 11:00 UTC, basil-conto approved these changes
Thanks!

2021-03-13 11:13 UTC, merged